version: 2
updates:

  # npm dependencies for both backend and frontend
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"

  # Go modules in the backend/go folder
  - package-ecosystem: "gomod"
    directory: "/backend/go"
    schedule:
      interval: "monthly"

  # Docker images in backend and frontend
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"

  # Kubernetes manifests in backend/kubernetes
  - package-ecosystem: "gitsubmodule"
    directory: "/backend/kubernetes"
    schedule:
      interval: "monthly"

  # Grafana dashboards in backend/grafana
  - package-ecosystem: "gitsubmodule"
    directory: "/backend/grafana"
    schedule:
      interval: "monthly"

  # Prometheus configuration in backend/prometheus
  - package-ecosystem: "gitsubmodule"
    directory: "/backend/prometheus"
    schedule:
      interval: "monthly"
