apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-management-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: event-management-backend
  template:
    metadata:
      labels:
        app: event-management-backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-uri-secret
                  key: MONGODB_URI
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: event-management-backend-service
spec:
  selector:
    app: event-management-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
