version: "3"
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: express-nginx
    ports:
      - "80:80"
    depends_on:
      - nest-api
