networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  express-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-api
    expose:
      - "8080"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}

    networks:
      - frontend
      - backend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: express-nginx
    ports:
      - "8081:8081"
    depends_on:
      - express-api
    networks:
      - frontend
