#Grafana configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    protocol = http
    http_port = 3001

    [security]
    admin_user = admin

    [users]
    allow_sign_up = false

    [auth.anonymous]
    enabled = true

    [log]
    mode = console
    level = info

  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: "15s"
          queryTimeout: "30s"
        editable: true
---
# Prometheus configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:

    rule_files:

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:3001']
      
      - job_name: 'express-api'
        static_configs:
          - targets: ['express-api:8080']
        metrics_path: '/metrics'
        scheme: 'http'

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
---
# Redis configMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    # Main Redis configuration
    bind 0.0.0.0
    port 6379
    
    # Security settings
    protected-mode yes
    # Use placeholder that will be replaced with actual password
    requirepass ${REDIS_PASSWORD}
    
    # ACL configuration
    user default on >${REDIS_PASSWORD} ~* &* +@all
    
    # Memory management
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    
    # Performance tuning
    appendonly yes
    appendfsync everysec
    
    # Connection settings
    timeout 0
    tcp-keepalive 300
    
    # Snapshotting
    save 900 1
    save 300 10
    save 60 10000