# Grafana PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/grafana
    type: DirectoryOrCreate
---
# PostgreSQL PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres
    type: DirectoryOrCreate
---
# pgAdmin PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pgadmin
    type: DirectoryOrCreate
---
# Prometheus PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/prometheus
    type: DirectoryOrCreate
