# Grafana PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/grafana
    type: DirectoryOrCreate
---
# PostgreSQL PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres
    type: DirectoryOrCreate
---
# pgAdmin PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pgadmin
    type: DirectoryOrCreate
---
# Prometheus PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/prometheus
    type: DirectoryOrCreate
---
# Go Backup PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-backup-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/db-backup
    type: DirectoryOrCreate
---
# Redis PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    type: local
    app: redis
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/redis
    type: DirectoryOrCreate
---
# Jenkins Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/jenkins