# Express API Service
apiVersion: v1
kind: Service
metadata:
  name: express-api # The name of the Express API service
spec:
  selector:
    app: express-api # Selects pods labeled with 'app: express-api'
  ports:
    - protocol: TCP
      port: 8080 # Exposes port 8080 on the Service
      targetPort: 8080 # Forwards traffic to port 8080 on the container
  type: ClusterIP # Internal service, not exposed directly

---
# Nginx Service
apiVersion: v1
kind: Service
metadata:
  name: nginx # The name of the Nginx service
spec:
  type: LoadBalancer # The service is exposed externally
  selector:
    app: nginx # Selects pods labeled with 'app: nginx'
  ports:
    - protocol: TCP
      port: 8081 # Exposes port 8081 on the Service
      targetPort: 8081 # Forwards traffic to port 8081 on the container

---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres # The name of the PostgreSQL service
spec:
  selector:
    app: postgres # Selects pods labeled with 'app: postgres'
  ports:
    - protocol: TCP
      port: 5432 # Exposes port 5432 on the Service
      targetPort: 5432 # Forwards traffic to port 5432 on the container
  type: ClusterIP # Internal database

---
# pgAdmin Service
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  selector:
    app: pgadmin # Selects pods labeled with 'app: pgadmin'
  ports:
    - protocol: TCP
      port: 8082 # Exposes port 8082 on the Service
      targetPort: 80 # Forwards traffic to port 80 on the container
      nodePort: 30001
  type: NodePort
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer # Exposing frontend externally
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
# Grafana service
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002
  type: NodePort
---
# Prometheus Service
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30003
  type: NodePort
