apiVersion: v1 # Specifies the API version for the Service resource
kind: Service # Defines the type of Kubernetes resource (Service)
metadata:
  name: express-api # Name of the Service resource

spec:
  selector:
    app: express-api # Selects the pods labeled with 'app: express-api'
  ports:
    - protocol: TCP # Specifies the protocol (TCP) for the Service
      port: 8080 # Exposes port 8080 on the Service
      targetPort: 8080 # Forwards traffic to port 8080 on the container
---
apiVersion: v1 # Specifies the API version for the Service resource
kind: Service # Defines the type of Kubernetes resource (Service)
metadata:
  name: nginx # Name of the Service resource

spec:
  type: LoadBalancer # The Service type is LoadBalancer, which exposes the Service externally
  selector:
    app: nginx # Selects the pods labeled with 'app: nginx'
  ports:
    - protocol: TCP # Specifies the protocol (TCP) for the Service
      port: 8081 # Exposes port 8081 on the Service
      targetPort: 8081 # Forwards traffic to port 8081 on the container
