apiVersion: 1
groups:
    - orgId: 1
      name: 1m group
      folder: Node.js Monitoring
      interval: 1m
      rules:
        - uid: ce413gjaykkqod
          title: Memory Usage
          condition: D
          data:
            - refId: A
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: node_memory_bytes{type="used"}
                instant: false
                interval: ""
                intervalMs: 15000
                legendFormat: Used
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: node_memory_bytes{type="total"}
                instant: false
                interval: ""
                intervalMs: 15000
                legendFormat: Total
                maxDataPoints: 43200
                range: true
                refId: B
            - refId: D
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 90
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - D
                      reducer:
                        params: []
                        type: last
                      type: query
                      unloadEvaluator:
                        params:
                            - 90
                        type: lt
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: E
                intervalMs: 1000
                maxDataPoints: 43200
                refId: D
                type: threshold
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: C
                type: reduce
            - refId: E
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: (${C} / ${F}) * 100
                intervalMs: 1000
                maxDataPoints: 43200
                refId: E
                type: math
            - refId: F
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: F
                type: reduce
          dashboardUid: nodejs-monitoring
          panelId: 2
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: nodejs-monitoring
            __panelId__: "2"
            description: This alert indicates that memory usage on the Node.js application server has exceeded 80% of total memory.
            runbook_url: http://localhost:30002/d/nodejs-monitoring/node-js-application-monitoring?from=2024-10-24T00:00:00.000Z&to=2024-10-27T16:57:29.091Z&timezone=browser&var-route=$__all&var-status_code=$__all&refresh=30s
            summary: Memory usage exceeded 90%.
          labels:
            Application: Node.js
            Environment: production
          isPaused: false
          notification_settings:
            receiver: aleksakovacevic@gmail.com
