openapi: 3.0.0
info:
  title: Booking Event API - Event Routes
  version: 1.0.0
  description: Routes for viewing and managing events

paths:
  /view/events:
    get:
      summary: Retrieve all events
      tags:
        - Events
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully retrieved events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '500':
          description: Server error

  /view/events/{id}:
    get:
      summary: Retrieve a specific event by ID
      tags:
        - Events
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Event not found
        '500':
          description: Server error

  /edit/events/{id}:
    patch:
      summary: Update an event
      tags:
        - Events
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                date:
                  type: string
                  format: date-time
                location:
                  type: string
                totalPeople:
                  type: number
                maxPeople:
                  type: number
      responses:
        '200':
          description: Event successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Invalid event ID
        '404':
          description: Event not found
        '500':
          description: Server error