name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install root dependencies
        run: npm ci --include=dev

      - name: Install backend dependencies
        run: npm ci --prefix ./backend

      - name: Install frontend dependencies
        run: npm ci --prefix ./frontend

      - name: Run all tests
        run: npm run all-test

      - name: Upload test results
        if: failure() # Upload results only if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results
