name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install root dependencies
        run: npm install

      - name: Install backend dependencies
        run: npm install --prefix ./backend

      - name: Install frontend dependencies
        run: npm install --prefix ./frontend

      - name: Run backend tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm test --prefix ./backend

      - name: Run frontend tests
        run: npm test --prefix ./frontend

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results
