name: Run Tests

on:
  push:
    branches:
      - main  # Postavite ovde naziv glavne grane, npr. `main` ili `master`
  pull_request:
    branches:
      - main  # Postavite ovde naziv grane za PR-ove

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Postavite verziju Node.js koju koristite

    - name: Install dependencies
      run: npm install

    - name: Run all tests
      run: npm run all-test

    - name: Upload test results
      if: failure()  # Upload results only if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./test-results 
